# Generated by Django 3.1.4 on 2020-12-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image_url',
            field=models.ImageField(default='https://www.cmcaindia.org/wp-content/uploads/2015/11/default-profile-picture-gmail-2.png', upload_to=''),
        ),
    ]
